### PR TITLE
Changed defaults. Added barnyard pkg var

### PR DESCRIPTION
**Pull request by craig-br**
Depends-on: https://github.com/ansible-security/ids_install/pull/13

### Issue
- Role defaults point to a defunct S3 bucket causing the role to fail
- Static entries in playbooks meant that current vars supplied were not enough

### Resolution
**defaults/main.yml**
- updated default values
- created a new var called  ```ids_install_snort_barnyard_pkg``` 

**tasks/main.yml**
- referenced ``ids_install_snort_barnyard_pkg```

### CODE REVIEW

**Comment by craig-br** [comment]
@justjais . May I please ask you to review. I need it for the security workshop.

**Comment by justjais** [comment]
@craig-br changes LGTM can you plz fix the linter failures, before we can merge the PR

**Comment by justjais** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Review by justjais — APPROVED** [review]

**Pull request merged**
