### PR TITLE
To update tox file for fixing linting failures

### PR DESCRIPTION
**Pull request by justjais**

### CODE REVIEW

**Comment by pabelanger** [comment]
@justjais we should drop the ansible-tox-molecule job for now too. That's likely in project-config

**Comment by justjais** [comment]
@pabelanger ack, and for the PR changes `ansible-tox-linters` failed, with the following error: `ERROR: InvocationError for command could not find executable black`

**Comment by pabelanger** [comment]
you need to at it to test-requirements.txt eg: https://github.com/ansible-collections/vyos.vyos/blob/main/test-requirements.txt#L1

**Comment by justjais** [comment]
@pabelanger ah ok, thanks for the swift response

**Comment by goneri** [comment]
I think the disk space problem comes from the fact you pull the full Ansible distribution, the whole thing is pretty large.
Can you try this: https://github.com/ansible-security/ids_install/pull/14

**Comment by goneri** [comment]
You need to configure yamllint to ignore the .tox directory. e.g: https://github.com/ansible-collections/community.vmware/blob/main/tox.ini#L20

**Pull request merged**
